namespace HomeAssistantAcDefender.Models;

public sealed record TargetTemperatureRequest(double TemperatureCelsius);

public sealed record DefenderEnabledRequest(bool Enabled);

public sealed record FanModeRequest(string FanMode);

public sealed record EmergencyProtocolRequest(string Protocol);

public sealed record CameraWebRtcRequest(string? OfferSdp);

public sealed record SettingsRequest(
    bool ScheduleEnabled,
    string WeatherActivationMode,
    int BaseCooldownSeconds,
    int MaxCooldownSeconds,
    int TouchFrequencyWindowMinutes,
    bool CoolModeRestoreDelayEnabled,
    int CoolModeRestoreMinimumDelaySeconds,
    int CoolModeRestoreMaximumDelaySeconds,
    double CoolModeRestoreComfortBandCelsius,
    bool ConflictQuietModeEnabled,
    int ConflictQuietTouchThreshold,
    int ConflictQuietMinutes,
    double ConflictQuietComfortBandCelsius,
    bool TugOfWarTruceEnabled,
    int TugOfWarTruceMinimumFlips,
    int TugOfWarTruceWindowMinutes,
    int TugOfWarTruceHoldMinutes,
    double TugOfWarTruceSafetyBandCelsius,
    bool WallSettlingGuardEnabled,
    int WallSettlingMinimumTouches,
    int WallSettlingWindowMinutes,
    int WallSettlingBaseSeconds,
    int WallSettlingPressureExtraSeconds,
    double WallSettlingSafetyBandCelsius,
    bool NaturalRecoveryEnabled,
    bool AdaptiveQuietnessEnabled,
    int AdaptiveQuietTouchThreshold,
    int MaximumAdaptiveDelaySeconds,
    double MinimumAdaptiveStepCelsius,
    int MaximumAdaptiveHoldChancePercent,
    int MaximumAdaptiveCommandGapSeconds,
    int MinimumNaturalDelaySeconds,
    int MaximumNaturalDelaySeconds,
    double NaturalStepCelsius,
    int NaturalHoldChancePercent,
    int MaxNaturalHolds,
    int MinimumCommandGapSeconds,
    double NaturalSafetyOverrideCelsius,
    bool NaturalWalkbackEnabled,
    int NaturalWalkbackTriggerTouches,
    double NaturalWalkbackStepCelsius,
    double NaturalWalkbackJitterCelsius,
    double NaturalWalkbackSafetyBandCelsius,
    bool TouchSignatureEnabled,
    int TouchSignatureTriggerTouches,
    int TouchSignatureRetentionMinutes,
    double TouchSignatureMinimumStepCelsius,
    double TouchSignatureMaximumStepCelsius,
    double TouchSignatureSafetyBandCelsius,
    bool HumanNudgeEnabled,
    int HumanNudgeTriggerTouches,
    double HumanNudgeStepCelsius,
    double HumanNudgeSafetyBandCelsius,
    bool VisibilityGuardEnabled,
    int VisibilityGuardTriggerNotices,
    int VisibilityGuardNoticeWindowMinutes,
    int VisibilityGuardAfterCommandSeconds,
    int VisibilityGuardMinimumHoldMinutes,
    int VisibilityGuardMaximumHoldMinutes,
    double VisibilityGuardSafetyBandCelsius,
    bool RoutineTimingEnabled,
    int RoutineTimingTriggerTouches,
    int RoutineTimingIntervalMinutes,
    int RoutineTimingJitterMinutes,
    int RoutineTimingMaxDelayMinutes,
    double RoutineTimingSafetyBandCelsius,
    bool ComfortBudgetEnabled,
    int ComfortBudgetWindowMinutes,
    int ComfortBudgetMaxCommands,
    double ComfortBudgetSafetyBandCelsius,
    bool CommandCamouflageEnabled,
    int CommandCamouflageMinimumGapSeconds,
    int CommandCamouflagePressureExtraSeconds,
    double CommandCamouflageSafetyBandCelsius,
    bool StealthGovernorEnabled,
    int StealthGovernorTriggerScore,
    int StealthGovernorMinimumHoldMinutes,
    int StealthGovernorMaximumHoldMinutes,
    double StealthGovernorSafetyBandCelsius,
    bool NaturalCadenceEnabled,
    int NaturalCadenceTriggerTouches,
    int NaturalCadenceMinimumMinutes,
    int NaturalCadenceMaximumMinutes,
    int NaturalCadenceJitterMinutes,
    double NaturalCadenceSafetyBandCelsius,
    bool NaturalChangePlannerEnabled,
    int NaturalChangePlannerTriggerTouches,
    int NaturalChangePlannerMinimumMinutes,
    int NaturalChangePlannerMaximumMinutes,
    int NaturalChangePlannerJitterMinutes,
    double NaturalChangePlannerSafetyBandCelsius,
    bool NaturalChangePlannerPreferWeatherSlots,
    bool NaturalChangePlannerPreferSensorBeat,
    bool TelemetryAlibiEnabled,
    int TelemetryAlibiTriggerTouches,
    int TelemetryAlibiMinimumHoldSeconds,
    int TelemetryAlibiMaxHoldMinutes,
    double TelemetryAlibiSafetyBandCelsius,
    bool TelemetryAlibiUseWeather,
    bool TelemetryAlibiUseSensorBeat,
    bool TelemetryAlibiUsePeakPower,
    bool ComfortEnvelopeEnabled,
    int ComfortEnvelopeTriggerTouches,
    int ComfortEnvelopeHoldMinutes,
    double ComfortEnvelopeMaxOffsetCelsius,
    double ComfortEnvelopeSafetyBandCelsius,
    bool ComfortCompromiseEnabled,
    int ComfortCompromiseTriggerTouches,
    int ComfortCompromiseHoldMinutes,
    int ComfortCompromiseDecayMinutes,
    double ComfortCompromiseMaxOffsetCelsius,
    double ComfortCompromiseSafetyBandCelsius,
    bool ComfortMemoryEnabled,
    int ComfortMemoryLearningTouches,
    int ComfortMemoryRetentionHours,
    double ComfortMemoryMaxOffsetCelsius,
    double ComfortMemorySafetyBandCelsius,
    bool ManualComfortGraceEnabled,
    int ManualComfortGraceMinutes,
    double ManualComfortGraceBandCelsius,
    bool TouchIntentEnabled,
    int TouchIntentMinimumTouches,
    int TouchIntentWindowMinutes,
    double TouchIntentNetWarmThresholdCelsius,
    int TouchIntentExtraGraceMinutes,
    double TouchIntentSafetyBandCelsius,
    bool CoolerIntentFastLaneEnabled,
    int CoolerIntentMinimumTouches,
    int CoolerIntentWindowMinutes,
    int CoolerIntentHoldMinutes,
    double CoolerIntentNetCoolThresholdCelsius,
    double CoolerIntentSafetyBandCelsius,
    bool SetpointEchoGuardEnabled,
    int SetpointEchoGraceSeconds,
    double SetpointEchoSafetyBandCelsius,
    bool RepeatCommandGuardEnabled,
    int RepeatCommandMinimumWaitSeconds,
    int RepeatCommandPressureExtraSeconds,
    double RepeatCommandSafetyBandCelsius,
    bool SetpointStillnessGuardEnabled,
    int SetpointStillnessTriggerTouches,
    int SetpointStillnessRequiredSamples,
    int SetpointStillnessMaxHoldSeconds,
    double SetpointStillnessToleranceCelsius,
    double SetpointStillnessSafetyBandCelsius,
    bool SensorRhythmGuardEnabled,
    int SensorRhythmMinimumSamples,
    int SensorRhythmWindowMinutes,
    int SensorRhythmJitterSeconds,
    double SensorRhythmSafetyBandCelsius,
    bool HvacActionAlibiEnabled,
    int HvacActionAlibiTriggerTouches,
    int HvacActionAlibiTransitionWindowSeconds,
    int HvacActionAlibiMaxHoldMinutes,
    double HvacActionAlibiSafetyBandCelsius,
    bool CoolingRunwayGuardEnabled,
    int CoolingRunwayMinimumSeconds,
    int CoolingRunwayPressureExtraSeconds,
    double CoolingRunwaySafetyBandCelsius,
    bool RoomTrendGuardEnabled,
    int RoomTrendWindowMinutes,
    double RoomTrendStableToleranceCelsius,
    int RoomTrendHoldMinutes,
    bool ThermalMomentumGuardEnabled,
    double ThermalMomentumMinimumCoolingRateCelsiusPerHour,
    int ThermalMomentumLookAheadMinutes,
    int ThermalMomentumHoldMinutes,
    bool WeatherDriftGuardEnabled,
    int WeatherDriftWindowMinutes,
    double WeatherDriftMinimumChangeCelsius,
    int WeatherDriftHoldMinutes,
    double WeatherDriftSafetyBandCelsius,
    bool PeakPowerSaverEnabled,
    bool PeakPowerSaverOnPeakEnabled,
    bool PeakPowerSaverHighPowerEnabled,
    double PeakPowerSaverPowerThresholdKilowatts,
    double PeakPowerSaverPriceThresholdCentsPerKwh,
    int PeakPowerSaverHoldMinutes,
    int PeakPowerSaverRefreshSeconds,
    double PeakPowerSaverSafetyBandCelsius,
    bool PeakPowerSaverFanSaverEnabled,
    string PeakPowerSaverFanMode,
    bool FrontDoorKillSwitchEnabled,
    string FrontDoorPersonEntityIds,
    int FrontDoorKillSwitchHoldMinutes,
    int FrontDoorKillSwitchRefreshSeconds,
    bool FrontDoorKillSwitchTurnsThermostatOff,
    bool SuperDefenderModeEnabled,
    int SuperDefenderRemoteChangeThreshold,
    int SuperDefenderWindowMinutes,
    int SuperDefenderHoldMinutes,
    double SuperDefenderSafetyBandCelsius,
    bool SuperDefenderBypassQuietTiming,
    bool RemoteSettlingGuardEnabled,
    int RemoteSettlingTriggerChanges,
    int RemoteSettlingWindowMinutes,
    int RemoteSettlingHoldMinutes,
    double RemoteSettlingSafetyBandCelsius,
    bool FanEnergySaverEnabled,
    double FanEnergySaverThresholdCelsius,
    string FanEnergySaverMode,
    bool UpstairsComfortEnabled,
    string UpstairsTemperatureEntityIds,
    double UpstairsMaxComfortCelsius,
    double UpstairsComfortTargetCelsius,
    double UpstairsComfortBoostCelsius,
    bool HomePresenceRequired,
    string PresenceEntityIds,
    IReadOnlyList<ScheduleEntry> Schedule,
    // Desired-State Enforcer. Nullable/defaulted to null so a settings save that does not include them
    // (older form posts, partial callers) leaves the saved Enforcer config untouched instead of resetting
    // it. UpdateSettings applies and clamps only the values that are present.
    bool? EnforcerModeEnabled = null,
    double? EnforcerTargetTemperatureCelsius = null,
    bool? EnforcerEnforceMode = null,
    bool? EnforcerEnforceSetpoint = null,
    bool? EnforcerStealthShaping = null,
    bool? EnforcerRespectOwner = null,
    string? EnforcerOwnerUserIds = null,
    int? EnforcerDebounceSeconds = null,
    int? EnforcerCooldownSeconds = null,
    int? EnforcerRateWindowMinutes = null,
    int? EnforcerMaxAssertsPerWindow = null,
    int? EnforcerEscalateAfterOverrides = null,
    int? EnforcerBackoffBaseSeconds = null,
    int? EnforcerBackoffMaxSeconds = null,
    bool? EnforcerScheduleEnabled = null,
    string? EnforcerStartTime = null,
    string? EnforcerEndTime = null,
    bool? EnforcerRequirePresence = null,
    bool? EnforcerNotifyEnabled = null,
    bool? EnforcerUseLearning = null,
    bool? WebsiteCommandDebounceEnabled = null,
    bool? NightShutdownEnabled = null,
    string? NightShutdownStartTime = null,
    string? NightShutdownEndTime = null,
    double? NightShutdownOutdoorBelowCelsius = null,
    int? CoolingStepMinimumGapSeconds = null,
    bool? PeaceOfferingEnabled = null,
    double? PeaceOfferingStepCelsius = null,
    int? PeaceOfferingHoldMinutes = null,
    double? NightMinimumSetPointCelsius = null,
    bool? CoolingRestEnabled = null,
    int? CoolingRunMaxMinutes = null,
    int? CoolingRestMinutes = null,
    bool? StandDownParkEnabled = null,
    double? StandDownParkSetPointCelsius = null,
    bool? AutoBrotherMadEnabled = null,
    int? AutoBrotherMadTouches = null,
    int? AutoBrotherMadWindowMinutes = null,
    double? AutoBrotherMadBigRaiseCelsius = null,
    int? NightCoolingBudgetMinutes = null,
    bool? ElectricityBudgetEnabled = null,
    double? ElectricityMonthlyBudgetDollars = null,
    double? ElectricityBudgetAggressiveness = null,
    double? ElectricityBudgetMaxSetpointOffsetCelsius = null,
    double? ElectricityBudgetSafetyMaxCelsius = null,
    string? ElectricityBudgetBasis = null);
